### ISSUE TITLE
[BUG] `wash dev` with JSON output will panic when piped into `jq`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#3639]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

For some reason, when setting the OutputKind to `json` for `wash dev` it will panic when writing the final println to stdout:
```console
RUST_BACKTRACE=full wash dev --work-dir ../../examples/rust/components/http-hello-world -o json |jq
ℹ️  Resolved wash session ID [OnHClf]
🚧 Starting a new host...
👀 Found wadm version on the disk: wadm-cli 0.18.0
...
🔁 Reloading component [OnHClf-http-hello-world]...
👀 Watching for file changes (press Ctrl+c to stop)...
^C
🛑 Received Ctrl + c, stopping devloop...
🧹 Cleaning up deployed WADM application(s)...
⏳ Stopping wasmCloud instance...
⏳ Stopping wadm...
✅ Dev session exited successfully
thread 'main' panicked at std/src/io/stdio.rs:1117:9:
failed printing to stdout: Broken pipe (os error 32)
stack backtrace:
   0:        0x1067a6614 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x1067c92fc - core::fmt::write::ha36a8060c13608ea
   2:        0x1067a17ac - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x1067a7b50 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x1067a7700 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x1067a85cc - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   6:        0x1067a7ff8 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   7:        0x1067a6ad8 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   8:        0x1067a7cc0 - _rust_begin_unwind
   9:        0x1068b9178 - core::panicking::panic_fmt::h410d3f147658259b
  10:        0x1067a0a0c - std::io::stdio::_print::h03106e215f254c7b
  11:        0x104f86828 - wash::main::{{closure}}::h036a5f64ca6393ab
  12:        0x104fdc44c - tokio::runtime::park::CachedParkThread::block_on::hd9a169b070f1c649
  13:        0x1050a3af8 - tokio::runtime::context::runtime::enter_runtime::h8cdacac60488dc28
  14:        0x10511fdf0 - tokio::runtime::runtime::Runtime::block_on::he678861ff8bd983d
  15:        0x10539c834 - wash::main::hcbb60b44a096691e
  16:        0x105338af4 - std::sys::backtrace::__rust_begin_short_backtrace::he1ea7d1dd13af531
  17:        0x1053ae7fc - std::rt::lang_start::{{closure}}::h627f04af2da6d9d8
  18:        0x106799e34 - std::rt::lang_start_internal::h9e88109c8deb8787
  19:        0x10539c934 - _main
```

### Steps to reproduce

1. Clone this repository
2. Install wash, or run `cargo run` from the `crates/wash-cli` directory
3. Point `--work-dir` to one of the simple examples that you have a local installation for, and set `-o json`

### Expected behavior

I would expect for this to work, because outputting to JSON works fine and so dies redirecting stdout to a file and then catting that file into jq. This is probably just a little edge case I'm missing

### Environment

- OS: [e.g. Linux, MacOS] MacOS
- Shell [e.g. bash, zsh, powershell] zsh
- wasmcloud Version [e.g. 0.81.0] 1.4.1

**Comment by michelm** [comment]
Please note the problem also occurs when using default (text) output and using a pipe:

```bash
mmooij@gandalf:~/dev/hello-wc2$ wash dev | xargs echo
ℹ️  Resolved wash session ID [JPTilU]
🚧 Starting a new host...
ℹ️  NATS server successfully started, using config @ [/home/mmooij/.wash/downloads/nats.conf]
ℹ️  NATS server logs written to [/home/mmooij/.wash/dev/JPTilU/nats.log]
👀 Found wadm version on the disk: wadm-cli 0.18.0
✅ Using wadm version [v0.18.0]
🔧 Successfully started wasmCloud instance
✅ Successfully started host, logs writing to /home/mmooij/.wash/dev/JPTilU/wasmcloud.log
🚧 Building project...
    Finished `release` profile [optimized] target(s) in 0.07s
✅ Successfully built project at [/home/mmooij/dev/hello-wc2/build/http_hello_world_s.wasm]
ℹ️  Detected component dependencies: {"http-server"}
🔁 Deployed development manifest for application [dev-jptilu-http-hello-world]
✨ HTTP Server: Access your application at http://127.0.0.1:8000
🔁 Reloading component [JPTilU-http-hello-world]...
👀 Watching for file changes (press Ctrl+c to stop)...
^C
🛑 Received Ctrl + c, stopping devloop...
🧹 Cleaning up deployed WADM application(s)...
⏳ Stopping wasmCloud instance...
⏳ Stopping wadm...
⏳ Stopping NATS...
✅ Dev session exited successfully
thread 'main' panicked at std/src/io/stdio.rs:1117:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by michelm** [comment]
When implementing a dummy 'wash dev' **handle_command()** function that just returns with "_Dev session exited successfully_" the problem does not occur (**src/cmd/dev/mod.rs**):

```rust
/// Handle `wash dev`
pub async fn handle_command(
    _cmd: DevCommand,
    _output_kind: wash_lib::cli::OutputKind,
) -> Result<CommandOutput> {
    let session_id = "dummy";

    Ok(CommandOutput::from_key_and_text(
        "result",
        format!(
            "{} Dev session [{session_id}] exited successfully.",
            emoji::GREEN_CHECK,
        ),
    ))
}
```

Command line result:
```bash
mmooij@gandalf:~/dev/hello-wc2$ RUST_BACKTRACE=full $HOME/dev/wasmcloud/target/debug/wash dev --nats-connect-only -o json | jq
{
  "success": true,
  "result": "✅ Dev session [dummy] exited successfully."
}
```

**Comment by michelm** [comment]
When sending a CTRL-C both processes will receive the signal and terminate if the second process first (**jq**), it will close its **stdin** effectively closing the **stdout** of _wash dev_, resulting in the broken pipe error. 

I tested and observed the same problem in a little test program:

```rust
use tokio::signal;

#[tokio::main]
async fn main() {
    for i in 1..10 {
        println!("[{}] the quick brown fox jumps over the lazy dog", i);
    }

    tokio::select! {
        ctrl_c = signal::ctrl_c() => {
            match ctrl_c {
                Ok(_) => {
                    println!("[CTRL^C] the quick brown fox jumps over the lazy dog");
                },
                Err(e) => {
                    eprintln!("\n[ERROR] failed to receive SIGINT: {:?}", e);
                }
            }
        }
    }

    println!("[EXIT] the quick brown fox jumps over the lazy dog");
}
```

Running without pipe:

```bash
mmooij@gandalf:~/dev/rusty-tokio$ RUST_BACKTRACE=full ./target/debug/rusty-signal-ctrlc
[1] the quick brown fox jumps over the lazy dog
[2] the quick brown fox jumps over the lazy dog
[3] the quick brown fox jumps over the lazy dog
[4] the quick brown fox jumps over the lazy dog
[5] the quick brown fox jumps over the lazy dog
[6] the quick brown fox jumps over the lazy dog
[7] the quick brown fox jumps over the lazy dog
[8] the quick brown fox jumps over the lazy dog
[9] the quick brown fox jumps over the lazy dog
^C[CTRL^C] the quick brown fox jumps over the lazy dog
[EXIT] the quick brown fox jumps over the lazy dog
```

Running with pipe to grep:

```bash
mmooij@gandalf:~/dev/rusty-tokio$ RUST_BACKTRACE=full ./target/debug/rusty-signal-ctrlc | grep -e quick
[1] the quick brown fox jumps over the lazy dog
[2] the quick brown fox jumps over the lazy dog
[3] the quick brown fox jumps over the lazy dog
[4] the quick brown fox jumps over the lazy dog
[5] the quick brown fox jumps over the lazy dog
[6] the quick brown fox jumps over the lazy dog
[7] the quick brown fox jumps over the lazy dog
[8] the quick brown fox jumps over the lazy dog
[9] the quick brown fox jumps over the lazy dog
^Cthread 'main' panicked at std/src/io/stdio.rs:1117:9:
failed printing to stdout: Broken pipe (os error 32)
stack backtrace:
   0:     0x562719deb15a - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x562719deb15a - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562719deb15a - std::sys::backtrace::_print_fmt::h8a221d40f5e0f88b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:     0x562719deb15a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:     0x562719e093fb - core::fmt::rt::Argument::fmt::h5da9c218ec984eaf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:     0x562719e093fb - core::fmt::write::hf5713710ce10ff22
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:     0x562719de88b3 - std::io::Write::write_fmt::hda708db57927dacf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:     0x562719dec442 - std::sys::backtrace::BacktraceLock::print::hbcdbec4d97c91528
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:     0x562719dec442 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:     0x562719dec0ae - std::panicking::default_hook::h81c8cd2e7c59ee33
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:     0x562719decc3f - std::panicking::rust_panic_with_hook::had2118629c312a4a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:     0x562719dec9b7 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:671:13
  12:     0x562719deb639 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:     0x562719dec644 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:     0x562719d1f463 - core::panicking::panic_fmt::h3eea515d05f7a35e
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
  15:     0x562719de7d3c - std::io::stdio::print_to::h87e0adeb3e048e42
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/stdio.rs:1117:9
  16:     0x562719de7d3c - std::io::stdio::_print::hd6837e34a66547dd
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/stdio.rs:1226:5
  17:     0x562719d2105f - rusty_signal_ctrlc::main::{{closure}}::hb5d40c036035c91b
                               at /home/mmooij/dev/rusty-tokio/src/bin/signal_ctrlc.rs:13:21
  18:     0x562719d26d0f - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h346181a90fcdc310
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:63
  19:     0x562719d2633c - tokio::runtime::coop::with_budget::h8b24cad565237e7b
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:107:5
  20:     0x562719d2633c - tokio::runtime::coop::budget::hcf3b41384d383dd4
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:73:5
  21:     0x562719d2633c - tokio::runtime::park::CachedParkThread::block_on::h59b425c840483fc6
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:31
  22:     0x562719d29f55 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h9365990aa0a25330
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/blocking.rs:66:9
  23:     0x562719d20510 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h58369234a1803acc
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  24:     0x562719d27126 - tokio::runtime::context::runtime::enter_runtime::h2e20df65d7ecc12d
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/runtime.rs:65:16
  25:     0x562719d2043e - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h2b9d7b61376f3505
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  26:     0x562719d284b1 - tokio::runtime::runtime::Runtime::block_on_inner::ha38e61aa80fc1f04
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:370:45
  27:     0x562719d28738 - tokio::runtime::runtime::Runtime::block_on::h0d9fe021342d1f77
                               at /home/mmooij/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:342:13
  28:     0x562719d2a542 - rusty_signal_ctrlc::main::hbfa01b5b8c725c14
                               at /home/mmooij/dev/rusty-tokio/src/bin/signal_ctrlc.rs:5:5
  29:     0x562719d216ab - core::ops::function::FnOnce::call_once::hf9b132ab2c0d2c8f
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  30:     0x562719d2820e - std::sys::backtrace::__rust_begin_short_backtrace::h43d2806160c49e28
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  31:     0x562719d21d61 - std::rt::lang_start::{{closure}}::h7924f0978940646f
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:164:18
  32:     0x562719de3750 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h08ecba131ab90ec4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:284:13
  33:     0x562719de3750 - std::panicking::try::do_call::hf33a59fd8ce953f4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  34:     0x562719de3750 - std::panicking::try::h5005ce80ce949fd8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  35:     0x562719de3750 - std::panic::catch_unwind::hfbae19e2e2c5b7ed
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  36:     0x562719de3750 - std::rt::lang_start_internal::{{closure}}::ha0331c3690741813
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:48
  37:     0x562719de3750 - std::panicking::try::do_call::hcdcbdb616b4d0295
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  38:     0x562719de3750 - std::panicking::try::h3f2f1725a07d2256
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  39:     0x562719de3750 - std::panic::catch_unwind::h51869e04b56b2dc3
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  40:     0x562719de3750 - std::rt::lang_start_internal::h4d90db0530245041
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:143:20
  41:     0x562719d21d3a - std::rt::lang_start::h3d0755fec0e928b0
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/rt.rs:163:17
  42:     0x562719d2a5ee - main
  43:     0x7f1e16467248 - __libc_start_call_main
  44:     0x7f1e1646730b - __libc_start_main@GLIBC_2.2.5
  45:     0x562719d1fed5 - _start
  46:                0x0 - <unknown>

```
 Although the above sometimes does not panic; I guess this depends on when the stdout is closed.

**Comment by michelm** [comment]
## Solutions

Proposed improvement and fixes:

1. Use buffered output writers for stderr and stdout 
2. Use sequential execution and capture **all** of stdout (and stderr) using a temp file as intermediate.

### Improvement 1 - use buffered output writer

Using a buffered output writer will prevent _wash dev_ from crashing with a broken pipe, as shown in the example program below:

```rust
use std::io::{self, stdout, BufWriter, Write};
use tokio::signal;

#[tokio::main]
async fn main() -> io::Result<()> {

    for i in 1..=5 {
        eprintln!("[{}] dog lazy the over jumps fox brown quick the", i);
        println!("[{}] the quick brown fox jumps over the lazy dog", i);
    }

    // Unbufferd writing to stdout is allowed up to this point.
    tokio::select! {
        ctrl_c = signal::ctrl_c()
            => {
                match ctrl_c {
                    Ok(_) => {
                        eprintln!("\n[I] the quick brown fox jumps over the lazy dog");
                    },
                    Err(e) => {
                        eprintln!("\n[ERROR] dog lazy the over jumps fox brown quick the: {:?}", e);
                    }
                }
            }
    }

    // Unbuffered writing to stdout|stderr is NOT allowed after this point when piped to another process.

    // This can crash when stderr is piped to another process.
    eprintln!("[F] dog lazy the over jumps fox brown quick the");

    // Buffered writing prevents crash when stdout is piped to another process; but not all output
    // may be captured by the other process in case of a CTRL^C signal.
    let mut stdout_buf = BufWriter::new(stdout().lock());
    match write!(stdout_buf, "[RESULT] the quick brown fox jumps over the lazy dog\n") {
        Ok(_) => {},
        Err(e) => {
            eprintln!("[E] failed to write to stdout: {:?}", e);
        }
    }

    match stdout_buf.flush() {
        Ok(_) => {},
        Err(e) => {
            eprintln!("[E] failed to flush stdout: {:?}", e);
        }
    }

    eprintln!("[X] dog lazy the over jumps fox brown quick the");
    Ok(())
}
```

Running the program with pipe to grep does not panic:

```console
mmooij@gandalf:~/dev/rusty-tokio$ ./target/debug/rusty-signal-ctrlc-bufwriter | grep -e quick
[1] dog lazy the over jumps fox brown quick the
[2] dog lazy the over jumps fox brown quick the
[3] dog lazy the over jumps fox brown quick the
[4] dog lazy the over jumps fox brown quick the
[5] dog lazy the over jumps fox brown quick the
[1] the quick brown fox jumps over the lazy dog
[2] the quick brown fox jumps over the lazy dog
[3] the quick brown fox jumps over the lazy dog
[4] the quick brown fox jumps over the lazy dog
[5] the quick brown fox jumps over the lazy dog
^C
[I] the quick brown fox jumps over the lazy dog
[F] dog lazy the over jumps fox brown quick the
[E] failed to flush stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[X] dog lazy the over jumps fox brown quick the

```

Notice the result message on stdout is missing , since the pipe has been closed. Instead the error message is printed.

### Improvement 2 - use sequential execution to capture all output

In the documentation add a remark on how all output can be captured by a piped command.

```console
mmooij@gandalf:~/dev/rusty-tokio$ (./target/debug/rusty-signal-ctrlc-bufwriter 1>/tmp/rusty.out; grep -e quick -i /tmp/rusty.out; rm /tmp/rusty.out)
[1] dog lazy the over jumps fox brown quick the
[2] dog lazy the over jumps fox brown quick the
[3] dog lazy the over jumps fox brown quick the
[4] dog lazy the over jumps fox brown quick the
[5] dog lazy the over jumps fox brown quick the
^C
[I] the quick brown fox jumps over the lazy dog
[F] dog lazy the over jumps fox brown quick the
[X] dog lazy the over jumps fox brown quick the
[1] the quick brown fox jumps over the lazy dog
[2] the quick brown fox jumps over the lazy dog
[3] the quick brown fox jumps over the lazy dog
[4] the quick brown fox jumps over the lazy dog
[5] the quick brown fox jumps over the lazy dog
[RESULT] the quick brown fox jumps over the lazy dog
```

**Comment by brooksmtownsend** [comment]
Nice work here @michelm with #3680
